#ifndef PROCESS_H
#define PROCESS_H

#include <stdint.h>
#include <x86_64/memory/paging.h>
#include <asm/mm.h>

#define NUM_PROCESSES 10
#define NUM_CPUS 2

/* +1 for guard page. the idea being we unmap
 * the last page on the stack (grows down), and
 * add logic to the page fault interrupt to detect
 * if the page is unmapped and at some offset
 * from a kernel stack base. if so, say something like
 * "stack overflow on <pid>". i believe it's sufficient
 * to clear the PRESENT bit on the page, and invalidate_page().
 * for now, we overcompensate with a largened stack. 16 KiB
 * should be more than enough, it's what linux uses (although
 * linux handles thousands+ (?) processes at a time, so there's
 * a memory pressure on smaller devices).
 * TODO(fact check)
 * TODO(later)
 */
#define KSTACK_PAGES 32
#define KSTACK_SIZE ((KSTACK_PAGES + 1) * PAGE_SIZE)

// RFLAGS bits, generated by clod:

/* Intel SDM Vol. 1, §3.4.3 */
/* Status flags — written by arithmetic/logic instructions */
#define FL_CF 0x00000001 /* bit  0: carry — unsigned overflow/borrow      */
/*         also the result bit of bt/bts/btr     */
#define FL_RESERVED1 \
	0x00000002 /* bit  1: reserved, always reads 1              */
#define FL_PF 0x00000004 /* bit  2: parity — even # of set bits in low 8  */
#define FL_AF 0x00000010 /* bit  4: adjust — carry out of bit 3, for BCD  */
#define FL_ZF 0x00000040 /* bit  6: zero — result was 0                   */
#define FL_SF 0x00000080 /* bit  7: sign — copy of the result's high bit  */
#define FL_OF 0x00000800 /* bit 11: overflow — signed overflow            */

/* Control flags */
#define FL_TF 0x00000100 /* bit  8: trap — raise #DB after every instr;   */
/*         this is how single-stepping works     */
#define FL_IF 0x00000200 /* bit  9: interrupt enable — sti sets, cli      */
/*         clears. Maskable IRQs only.           */
#define FL_DF 0x00000400 /* bit 10: direction — 1 = string ops (movs,     */
/*         stos) walk downward. cld before use.  */

/* System flags */
#define FL_IOPL 0x00003000 /* bits 12-13: I/O privilege level (2-bit field) */
#define FL_IOPL_SHIFT 12 /*         gates in/out and cli/sti for CPL > 0  */
#define FL_NT 0x00004000 /* bit 14: nested task — legacy hardware task    */
/*         switching; meaningless in long mode   */
#define FL_RF 0x00010000 /* bit 16: resume — suppress instruction         */
/*         breakpoints for one instruction       */
#define FL_VM 0x00020000 /* bit 17: virtual-8086 mode; unavailable in     */
/*         long mode                             */
#define FL_AC 0x00040000 /* bit 18: alignment check (with CR0.AM) —       */
/*         doubles as SMAP override via stac/clac*/
#define FL_VIF 0x00080000 /* bit 19: virtual interrupt flag (VME/PVI)      */
#define FL_VIP 0x00100000 /* bit 20: virtual interrupt pending             */
#define FL_ID 0x00200000 /* bit 21: writable iff CPUID is supported —     */
/*         the classic CPUID detection trick     */
/* Bits 3, 5, 15, 22-63 are reserved and read as 0 */

// TODO(userspace)
// track TSS and load new SS and ESP on context switch for switching
// to a higher privilege level

struct context {
	/* stack frame */
	virt_addr_t rsp;
	//virt_addr_t rbp; // not necessary

	int intena;
	int noff;

	/* general purpose registers (not callee-saved between functions) */
	uint64_t rbx;
	uint64_t r12;
	uint64_t r13;
	uint64_t r14;
	uint64_t r15;

	// ffu, mmx, see registers etc. (not currently used)
};

enum process_state {
	UNUSED, // (i believe) c standard guarantees this will
	// be default-0-initialized, so we include
	// this UNUSED value to prevent the scheduler
	// from accidentally using empty (bss'ed) data.
	READY,
	RUNNING,
	SLEEPING,
	ZOMBIE
};

struct cpu {
	int cpuid;
	int intena;
	int noff;

	// currently running process
	struct process *task;

	// the scheduler runs as a process with a stack of its own, so that control
	// can be handed back to it without borrowing the stack of whoever was
	// interrupted. it is not on the mlfq -- it is what services the mlfq.
	struct process *scheduler_proc;
};

void init_process(void);

extern struct cpu cpus[NUM_CPUS];

extern uint8_t __glbl_pid;

struct addrspace {
	phys_addr_t p4d_base; // pass to cr3
	p4d_t *p4d;
	// TODO(cleanup) ideally, we'd like to add a guard page
	// at the end of the stack. we currently do that, but we don't
	// have logic within the page fault handler to detect this.
	// for now, we can just have two pointers, and compare if
	// our accesses ever exceed the end of the stack. this
	// adds on an unnecessary, expensive operation for now!

	struct list_head vm_list; // linked list of vm_region
};

struct process {
	uint8_t pid;
	char name[32];

	struct process *parent;
	struct addrspace addrspace;

	// entry into multilevel feedback queue in scheduler
	struct list_head sched;

	enum process_state state;
	phys_addr_t cr3;
	struct context context;

	// where the process starts on its very first run. swtch()'s ret always
	// lands in forkret(), which does the first-run housekeeping and then calls
	// this -- a fresh process has no real return address to go back to.
	void (*entry)(void);
};

void sched(void);
int fork(const char *name, void (*entry)(void), int level);

struct process *myproc();
struct cpu *mycpu();

uint64_t irq_save(void);
void irq_restore(uint64_t flags);

#endif
